version: '3'

networks:
  laravel:

volumes: 
  dbdata:

services:

    nginx:
      image: nginx:alpine
      container_name: webserver
      ports:
        - "8080:80"
      volumes:
        - ./src:/var/www/html
        - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - database
      networks:
        - laravel

    php:
      build:
        context: .
        dockerfile: ops/php-fpm/Dockerfile
      container_name: php
      volumes:
        - ./src:/var/www/html
      ports:
        - "9000:9000"
      networks:
        - laravel

    database:
      image: postgres:13
      container_name: database
      restart: unless-stopped
      tty: true
      ports:
        - "5432:5432"
      volumes:
        - dbdata:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: melkor
        POSTGRES_PASSWORD: secretpassword
        POSTGRES_DB: laravel
      networks:
        - laravel

